/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package trippy_player.trippy_player;

import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Hp
 */
public class Create_Playlist extends javax.swing.JInternalFrame {

    /**
     * Creates new form Create_Playlist
     */
    
    private javax.swing.JFileChooser fileChooser;
    
    main nMain;
    File[] files;
    
    
    public Create_Playlist(main _main) {
        nMain = _main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Enter Playlist Name:");

        jButton1.setText("Add Files");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save Playlist");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            fileChooser = new JFileChooser();

            fileChooser.setMultiSelectionEnabled(true);
            
            fileChooser.setAcceptAllFileFilterUsed(false);

            fileChooser.setDialogTitle("Select a .mp3 file");

            FileNameExtensionFilter restrict = new FileNameExtensionFilter("Only .mp3 files", "mp3");
            fileChooser.addChoosableFileFilter(restrict);

            int response = fileChooser.showOpenDialog(null);

            if (response == JFileChooser.APPROVE_OPTION) {

                    files = fileChooser.getSelectedFiles();
                    
                    int size;
                    size = files.length;
                    
                    String[] file_names = new String[size];
                    
                    int i = 0;
                    
                    while(i < size) {
                        file_names[i] = files[i].getName();
                        i++;
                    }
                    
                    jList1.setListData(file_names);
            } else {
                System.out.println("Failed Opening File|");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/trippyPlayer";
            String username="root";
            String pass="123456";
            Connection con = null;
            
            
            con = DriverManager.getConnection (url , username ,pass);
            
            String playName = jTextField1.getText();
            String query = "insert into playlist values(?,?)";
            PreparedStatement pt = con.prepareStatement(query);
            pt.setString(2,playName);
            pt.setInt(1, 0);
            
            pt.executeUpdate();
            
            System.out.println("Inserted");
            
            String query_2 = "select playID from playlist where playName = \'" + playName + "\'";
            pt = con.prepareStatement(query_2);
            ResultSet rs = pt.executeQuery();
            
            rs.next();
            int playID = rs.getInt("playID");
            
            
            int size;
            size = files.length;
            
            String[] file_names = new String[size];
            String[] file_locations = new String[size];
            
            int i = 0;
            
            while(i < size) {
                file_names[i] = files[i].getName();
                file_locations[i] = files[i].getAbsolutePath();
                i++;
            }
            
            int j = 0;
            
            
                String tableQuery = "insert into songsPlaylist values(?, ?, ?)";
                pt = con.prepareStatement(tableQuery);

            while (j < size) {
               
                pt.setInt(1, playID);
                pt.setString(2, file_names[j]);
                pt.setString(3, file_locations[j]);

                pt.executeUpdate();
                
                j++;
            }
            
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Create_Playlist.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Create_Playlist.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            nMain.loadPlaylists();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Create_Playlist.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Create_Playlist.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
