/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package trippy_player.trippy_player;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hp
 */
public class Show_Playlist extends javax.swing.JInternalFrame {

    /**
     * Creates new form Show_Playlist
     */
    String playlistName;
    main nMain;
    
    public Show_Playlist(String _text, main _main) {
        playlistName = _text;
        nMain = _main;
        initComponents();
        try {
            loadSongs();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Show_Playlist.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Show_Playlist.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadSongs() throws ClassNotFoundException, SQLException{
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url="jdbc:mysql://localhost:3306/trippyPlayer";
        String username="root";
        String pass="123456";
        Connection con = null;


        con = DriverManager.getConnection (url , username ,pass);

        String query = "select * from playlist where playName = \"" + playlistName + "\"";
        PreparedStatement pt = con.prepareStatement(query);
        ResultSet rs = pt.executeQuery();

        rs.next();
        int playlistID = rs.getInt("playID");
        
        String query_2 = "select * from songsPlaylist where playlistID = " + playlistID;
        pt = con.prepareStatement(query_2);
        ResultSet rs_2 = pt.executeQuery();
        
        int size = 0;
        while(rs_2.next()) {
            size++;
        }
        
        nMain.totalDBFiles = size;
        
        String[] file_names = new String[size];
        nMain.dbFileLocations = new String[size];
        nMain.dbFileNames = new String[size];
        
        rs_2.first();
        
        int i = 0;
        do{
            nMain.dbFileLocations[i] = rs_2.getString("songLocation");
            nMain.dbFileNames[i] = rs_2.getString("songName");
            file_names[i] = rs_2.getString("songName");
            i++;
        } while(rs_2.next());
        
        jList1.setListData(file_names);
        
        con.close();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Play Playlist");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        nMain.play_playList = true;
        nMain.play_playlistFun();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
